spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.pawqodqhlmbttllotryv
spring.datasource.password=7IiVRNHsEkDk8OGp
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Tuning for Supabase
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

# Required if using Transaction Mode (Port 6543)
# Disables client-side prepared statement caching to prevent 'cached plan' errors
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=validate
