spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Basic Connection
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.pawqodqhlmbttllotryv
spring.datasource.password=7IiVRNHsEkDk8OGp
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Tuning for Supabase
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

# Required if using Transaction Mode (Port 6543)
# Disables client-side prepared statement caching to prevent 'cached plan' errors
spring.datasource.hikari.data-source-properties.prepareThreshold=0


spring.jpa.hibernate.ddl-auto=update
telemetry.udp.enabled=false

# Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always
management.endpoint.env.show-values=always
management.endpoint.configprops.show-values=always
management.info.env.enabled=true

vaadin.async-supported=true
