#Racing League Tools Local Collector Settings
#Sat Jun 06 10:18:32 CEST 2026
telemetry.cloud.forward.enabled=true
telemetry.cloud.token=c4bd9196-7c56-4ef5-a6c5-6335ab18b3c4
telemetry.cloud.url=http\://localhost\:8080/api/telemetry
telemetry.recording.enabled=true
telemetry.recording.path=data/record_f126.bin
telemetry.udp.forward.enabled=false
telemetry.udp.forward.host=192.168.1.59
telemetry.udp.forward.port=20777
telemetry.udp.port=20777
