#Racing League Tools Local Collector Settings
#Thu Apr 30 19:34:39 CEST 2026
cloudForwardEnabled=true
cloudToken=c38befb8-f354-4ae2-aefe-1f97c689f0bc
cloudUrl=https\://racingleague.jabapage.be/api/telemetry
forwardEnabled=true
forwardHost=192.168.1.59
forwardPort=20777
port=20777
recordingEnabled=true
recordingPath=data/record_session.bin
