apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-server
  labels:
    app: cloud-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-server
  template:
    metadata:
      labels:
        app: cloud-server
    spec:
      containers:
      - name: cloud-server
        image: janverstuyft/racing_league:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Xss512K -Xmx256M -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=128M -XX:+UseSerialGC"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres.pawqodqhlmbttllotryv
        - name: SPRING_DATASOURCE_PASSWORD
          value: 7IiVRNHsEkDk8OGp
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: org.hibernate.dialect.PostgreSQLDialect
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION
          value: "true"
        - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
          value: "10"
        - name: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
          value: "5"
        - name: SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT
          value: "30000"
        - name: SPRING_DATASOURCE_HIKARI_MAX_LIFETIME
          value: "1800000"
        - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
          value: "20000"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "384Mi"
            cpu: "500m"
        volumeMounts:
        - name: data-storage
          mountPath: /data
      volumes:
      - name: data-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-server
spec:
  selector:
    app: cloud-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
