server.port=8081
telemetry.udp.port=20777
telemetry.cloud.url=http://localhost:8080/api/telemetry
telemetry.recording.enabled=false
telemetry.recording.path=data/recorded_session.bin
logging.level.be.jabapage.racingleague.collector=DEBUG
