server.port=8081
telemetry.udp.port=20777
telemetry.cloud.url=https://racingleague.jabapage.be/api/telemetry
telemetry.cloud.token=c38befb8-f354-4ae2-aefe-1f97c689f0bc
telemetry.recording.enabled=true
telemetry.recording.path=data/record_session.bin

telemetry.udp.forward.enabled=false
telemetry.udp.forward.host=192.168.1.59
telemetry.udp.forward.port=20777
