server.port=8081
telemetry.udp.port=20777
telemetry.cloud.url=https://racingleague.jabapage.be/api/telemetry
telemetry.cloud.token=<place your token here>
telemetry.recording.enabled=false
telemetry.recording.path=data/record_session.bin

telemetry.udp.forward.enabled=false
telemetry.udp.forward.host=192.168.1.59
telemetry.udp.forward.port=20777
